<!-- ItemForm.vue - Reusable Form Component for Create/Update -->
<!-- 
  Purpose: Handles form UI for creating and editing items.
  
  Vue.js Concepts demonstrated:
  - Props: Data passed from parent component (ItemView)
  - Emits: Events sent back to parent (save, cancel)
  - v-model: Two-way data binding
  - Computed properties: Dynamic values based on state
  - Form validation: Client-side input validation
  
  Interview talking points:
  - "I use props down, events up pattern for parent-child communication"
  - "Form validation prevents invalid data from reaching the backend"
-->

<script setup>
import { computed } from 'vue'

// Props: Data received from parent component
// form: The item data being edited (or empty for create)
// isEdit: Boolean flag to toggle between create/update mode
const props = defineProps({
  form: {
    type: Object,
    required: true,
  },
  isEdit: {
    type: Boolean,
    default: false,
  },
})

// Emits: Events to communicate back to parent
// save: Triggered when user clicks Save/Update
// cancel: Triggered when user clicks Cancel
const emit = defineEmits(['save', 'cancel'])

// Computed: Form title changes based on create/edit mode
// Interview point: "Computed properties are cached and only re-evaluate when dependencies change"
const formTitle = computed(() => props.isEdit ? 'Edit Item' : 'Add New Item')

// Computed: Button text changes based on mode
const saveButtonText = computed(() => props.isEdit ? 'Update' : 'Save')

// Form validation: Checks if all required fields are filled
const isValid = computed(() => {
  return props.form.name && props.form.name.trim() !== '' &&
         props.form.price != null && props.form.price >= 0
})

// Format price for display (Indonesian Rupiah)
const formatPrice = (value) => {
  if (!value) return 'Rp 0'
  return 'Rp ' + Number(value).toLocaleString('id-ID')
}
</script>

<template>
  <div style="border: 1px solid #ddd; padding: 16px; margin-bottom: 16px; border-radius: 8px; background: #f9f9f9;">
    <h2>{{ formTitle }}</h2>

    <!-- Code field: Read-only, auto-generated by backend -->
    <div v-if="isEdit" style="margin-bottom: 8px;">
      <label>Code: </label>
      <span style="color: #666; font-style: italic;">{{ form.code }} (auto-generated)</span>
    </div>

    <!-- Name field: Required -->
    <div style="margin-bottom: 8px;">
      <label>Name: </label>
      <input 
        v-model="form.name" 
        placeholder="Item name (required)" 
        style="padding: 4px;"
        required
      />
      <span v-if="!form.name" style="color: red; font-size: 12px;"> *Required</span>
    </div>

    <!-- Price field: Must be a positive number -->
    <div style="margin-bottom: 8px;">
      <label>Price: </label>
      <input 
        v-model.number="form.price" 
        type="number" 
        placeholder="Price" 
        min="0"
        style="padding: 4px;"
      />
      <span style="color: #666; font-size: 12px;"> ({{ formatPrice(form.price) }})</span>
    </div>

    <!-- Quantity field -->
    <div style="margin-bottom: 8px;">
      <label>Quantity: </label>
      <input 
        v-model.number="form.quantity" 
        type="number" 
        placeholder="Quantity" 
        min="0"
        style="padding: 4px;"
      />
    </div>

    <!-- Active checkbox -->
    <div style="margin-bottom: 8px;">
      <label>
        <input type="checkbox" v-model="form.active" />
        Active
      </label>
    </div>

    <!-- Description textarea -->
    <div style="margin-bottom: 12px;">
      <label>Description: </label><br />
      <textarea 
        v-model="form.description" 
        placeholder="Item description (optional)" 
        rows="3"
        style="width: 100%; padding: 4px;"
      ></textarea>
    </div>

    <!-- Action buttons -->
    <div>
      <button 
        @click="emit('save')" 
        :disabled="!isValid"
        :style="{ opacity: isValid ? 1 : 0.5, cursor: isValid ? 'pointer' : 'not-allowed' }"
      >
        {{ saveButtonText }}
      </button>

      <button @click="emit('cancel')" style="margin-left: 8px;">
        Cancel
      </button>
    </div>
  </div>
</template>
